### ISSUE TITLE
Cannot get version in WONDERLAND bot

### ISSUE THREAD

**Issue by nitro2** [dnh-bot/dnh-werewolf-bot#157]
```
!version
```

Error:

```
CRITICALfatal: No names found, cannot describe anything.
INFOIgnoring exception in on_message
INFOTraceback (most recent call last):
INFO  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/discord/client.py", line 343, in _run_event
INFO    await coro(*args, **kwargs)
INFO  File "/opt/render/project/src/bot.py", line 83, in on_message
INFO    await process_message(client, message)  # loop through all commands and do action on first command that match
INFO    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO  File "/opt/render/project/src/bot.py", line 40, in process_message
INFO    await command.parse_command(discord_client, game, message)
INFO  File "/opt/render/project/src/commands/command.py", line 51, in parse_command
INFO    tag = subprocess.check_output(["git", "describe", "--tags"]).decode('utf-8')  # git describe --tags
INFO          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO  File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
INFO    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
INFO           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
INFO    raise CalledProcessError(retcode, process.args,
INFOsubprocess.CalledProcessError: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
Feedback
Invite a Friend
Contact Support
```

**Comment by huybt22** [comment]
Fixed by adding a release tag
